version: "3.8"
services:
  database:
    image: mysql:5.7
    environment:
                MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

   
    ports:
      - "4606:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_laravel
    restart: always
    depends_on:
      - database
    ports:
      - 4001:80
    environment:
      PMA_HOST: database
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_laravel
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "1999:80"
    restart: always
    networks:
      - dev

  www:
    build: php
    container_name: www_docker_laravel
    ports:
      - "8660:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev: